"""
models.py — Database schema for ChoreHouse
Security design notes:
  - Passwords stored as bcrypt hashes only; plaintext never persisted
  - AuditEntry uses HMAC-SHA256 chaining: each entry commits to the previous
    entry's hash, making silent insertion/deletion/reordering detectable
  - Invite codes are generated via secrets.token_urlsafe (128-bit entropy)
  - Household data is scoped by household_id on every sensitive table;
    queries always filter by the caller's household to enforce confidentiality
"""

import hashlib
import hmac
import json
import secrets
from datetime import datetime, timezone

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


# ---------------------------------------------------------------------------
# Users
# ---------------------------------------------------------------------------

class User(db.Model):
    __tablename__ = "users"

    id            = db.Column(db.Integer, primary_key=True)
    username      = db.Column(db.String(64), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)   # bcrypt digest
    created_at    = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    memberships   = db.relationship("HouseholdMember", back_populates="user")

    def __repr__(self):
        return f"<User {self.username}>"


# ---------------------------------------------------------------------------
# Households
# ---------------------------------------------------------------------------

class Household(db.Model):
    __tablename__ = "households"

    id          = db.Column(db.Integer, primary_key=True)
    name        = db.Column(db.String(128), nullable=False)
    # 128-bit invite secret; re-generated by admin on demand
    invite_code = db.Column(db.String(32), unique=True, nullable=False,
                            default=lambda: secrets.token_urlsafe(16))
    created_at  = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    members     = db.relationship("HouseholdMember", back_populates="household")
    chores      = db.relationship("Chore", back_populates="household")
    audit_log   = db.relationship("AuditEntry", back_populates="household",
                                  order_by="AuditEntry.sequence_num")

    def __repr__(self):
        return f"<Household {self.name}>"


class HouseholdMember(db.Model):
    """Join table with role.  Role is either 'admin' or 'roommate'."""
    __tablename__ = "household_members"

    id           = db.Column(db.Integer, primary_key=True)
    user_id      = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    household_id = db.Column(db.Integer, db.ForeignKey("households.id"), nullable=False)
    # 'admin' or 'roommate' — enforced in application layer
    role         = db.Column(db.String(16), nullable=False, default="roommate")
    joined_at    = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    user         = db.relationship("User", back_populates="memberships")
    household    = db.relationship("Household", back_populates="members")

    __table_args__ = (
        db.UniqueConstraint("user_id", "household_id", name="uq_user_household"),
    )


# ---------------------------------------------------------------------------
# Chores
# ---------------------------------------------------------------------------

class Chore(db.Model):
    __tablename__ = "chores"

    id            = db.Column(db.Integer, primary_key=True)
    household_id  = db.Column(db.Integer, db.ForeignKey("households.id"), nullable=False)
    title         = db.Column(db.String(128), nullable=False)
    description   = db.Column(db.Text, default="")
    assigned_to   = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    due_date      = db.Column(db.Date, nullable=True)
    # 'pending' | 'complete' | 'disputed'
    status        = db.Column(db.String(16), nullable=False, default="pending")
    created_by    = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    created_at    = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    completed_at  = db.Column(db.DateTime, nullable=True)

    household     = db.relationship("Household", back_populates="chores")
    assignee      = db.relationship("User", foreign_keys=[assigned_to])
    creator       = db.relationship("User", foreign_keys=[created_by])
    complaints    = db.relationship("Complaint", back_populates="chore")


class Complaint(db.Model):
    __tablename__ = "complaints"

    id             = db.Column(db.Integer, primary_key=True)
    chore_id       = db.Column(db.Integer, db.ForeignKey("chores.id"), nullable=False)
    submitted_by   = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    description    = db.Column(db.Text, nullable=False)
    created_at     = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    resolved       = db.Column(db.Boolean, default=False)
    resolution     = db.Column(db.Text, nullable=True)
    resolved_by    = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    resolved_at    = db.Column(db.DateTime, nullable=True)

    chore          = db.relationship("Chore", back_populates="complaints")
    submitter      = db.relationship("User", foreign_keys=[submitted_by])
    resolver       = db.relationship("User", foreign_keys=[resolved_by])


# ---------------------------------------------------------------------------
# Audit log — cryptographically chained
# ---------------------------------------------------------------------------

# HMAC key stored in the database so it survives restarts.
# In a production system this would live in a hardware security module
# or at minimum an environment variable outside the DB.
class AuditHMACKey(db.Model):
    """Singleton row that holds the server-side HMAC key for audit entries."""
    __tablename__ = "audit_hmac_key"

    id  = db.Column(db.Integer, primary_key=True)
    key = db.Column(db.String(64), nullable=False,
                    default=lambda: secrets.token_hex(32))   # 256-bit key


class AuditEntry(db.Model):
    """
    Append-only audit log with HMAC-SHA256 chaining.

    Each entry's hash covers:
        household_id | sequence_num | timestamp | actor_id | action | details_json | prev_hash

    This makes the chain tamper-evident: editing any field in any entry,
    inserting a new entry, or deleting an entry will break the chain from
    that point forward.  Verification walks the chain and recomputes hashes.
    """
    __tablename__ = "audit_entries"

    id           = db.Column(db.Integer, primary_key=True)
    household_id = db.Column(db.Integer, db.ForeignKey("households.id"), nullable=False)
    sequence_num = db.Column(db.Integer, nullable=False)   # per-household counter
    timestamp    = db.Column(db.DateTime, nullable=False,
                             default=lambda: datetime.now(timezone.utc))
    actor_id     = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    action       = db.Column(db.String(64), nullable=False)   # e.g. "chore.complete"
    details_json = db.Column(db.Text, nullable=False, default="{}")
    prev_hash    = db.Column(db.String(64), nullable=False)   # hex digest of previous entry
    entry_hash   = db.Column(db.String(64), nullable=False)   # HMAC of this entry's fields

    household    = db.relationship("Household", back_populates="audit_log")
    actor        = db.relationship("User", foreign_keys=[actor_id])

    __table_args__ = (
        db.UniqueConstraint("household_id", "sequence_num",
                            name="uq_household_sequence"),
    )

    @staticmethod
    def _compute_hash(key_bytes: bytes, household_id: int, sequence_num: int,
                      timestamp: datetime, actor_id: int, action: str,
                      details_json: str, prev_hash: str) -> str:
        """Return hex HMAC-SHA256 over the canonical entry fields.

        Timestamps are normalised to naive UTC strings before hashing so that
        the hash is identical whether the datetime carries tzinfo or not
        (SQLite strips tzinfo on round-trip).
        """
        # Strip tzinfo for a stable, canonical string representation.
        ts_str = timestamp.replace(tzinfo=None).isoformat(timespec="microseconds")
        payload = "|".join([
            str(household_id),
            str(sequence_num),
            ts_str,
            str(actor_id),
            action,
            details_json,
            prev_hash,
        ]).encode()
        return hmac.new(key_bytes, payload, hashlib.sha256).hexdigest()

    @classmethod
    def append(cls, household_id: int, actor_id: int,
               action: str, details: dict) -> "AuditEntry":
        """
        Create and persist a new audit entry.
        Must be called inside an active db session (caller commits).
        """
        key_row = AuditHMACKey.query.first()
        key_bytes = bytes.fromhex(key_row.key)

        # Determine sequence number and previous hash
        last = (cls.query
                   .filter_by(household_id=household_id)
                   .order_by(cls.sequence_num.desc())
                   .first())
        if last is None:
            seq      = 1
            prev_h   = "0" * 64   # genesis sentinel
        else:
            seq      = last.sequence_num + 1
            prev_h   = last.entry_hash

        now          = datetime.now(timezone.utc)
        details_json = json.dumps(details, sort_keys=True)

        entry_hash = cls._compute_hash(
            key_bytes, household_id, seq, now, actor_id,
            action, details_json, prev_h
        )

        entry = cls(
            household_id = household_id,
            sequence_num = seq,
            timestamp    = now,
            actor_id     = actor_id,
            action       = action,
            details_json = details_json,
            prev_hash    = prev_h,
            entry_hash   = entry_hash,
        )
        db.session.add(entry)
        return entry

    @classmethod
    def verify_chain(cls, household_id: int) -> tuple[bool, str]:
        """
        Walk the entire audit chain for a household and recompute hashes.
        Returns (True, "OK") or (False, "<description of first violation>").
        """
        key_row = AuditHMACKey.query.first()
        key_bytes = bytes.fromhex(key_row.key)

        entries = (cls.query
                      .filter_by(household_id=household_id)
                      .order_by(cls.sequence_num)
                      .all())

        expected_prev = "0" * 64
        for entry in entries:
            if entry.prev_hash != expected_prev:
                return False, (
                    f"Entry #{entry.sequence_num}: prev_hash mismatch "
                    f"(expected {expected_prev[:8]}…, got {entry.prev_hash[:8]}…)"
                )
            recomputed = cls._compute_hash(
                key_bytes, entry.household_id, entry.sequence_num,
                entry.timestamp, entry.actor_id, entry.action,
                entry.details_json, entry.prev_hash,
            )
            if not hmac.compare_digest(recomputed, entry.entry_hash):
                return False, (
                    f"Entry #{entry.sequence_num}: HMAC mismatch — "
                    "entry data has been altered"
                )
            expected_prev = entry.entry_hash

        return True, "OK"
